Feature/find text
responsively-org/responsively-app pull request #400
Opened 2020-08-17 18:07 UTC by esprush

2020-08-19 03:37 UTC, jzabala requested changes
Great PR @esprush!

I just found some minor things.

- Add the find menu to the darwin menu too.

2020-08-19 03:37 UTC, jzabala commented on desktop-app/app/components/WebView/index.js
> +    // this.webviewRef.current.addEventListener('found-in-page', event => {
Remove unnecessary commented code.

2020-08-19 16:02 UTC, manojVivek commented
Updated UI: 
<img width="502" alt="Screenshot 2020-08-19 at 9 26 05 PM" src="https://user-images.githubusercontent.com/1283424/90660356-6dcccf00-e263-11ea-8341-dc2af47f4533.png">

2020-08-19 16:03 UTC, manojVivek commented
Converting this to a draft PR, as the feature is causing the app to crash occasionally. 
This can only be merged after that is figured out.

2020-08-19 18:24 UTC, jzabala commented
> Converting this to a draft PR, as the feature is causing the app to crash occasionally.
> This can only be merged after that is figured out.

Could you describe the test conditions or steps, and OS you used to crash the app while using the feature?

I tested it on Mac with different pages and the app never crashed.

2020-08-20 03:36 UTC, manojVivek commented
> @manojVivek Could you describe the test conditions or steps, and OS you used to crash the app while using the feature?
> 
> I tested it on Mac with different pages and the app never crashed.

@jzabala It was happening to me randomly, was not able to reproduce it with consistent steps though.
Mostly happened when I typed something, deleted and typed again quickly, or clicking the arrows multiple times after the search box is open idle for some time.

I'll check more today.

2020-10-11 07:06 UTC, manojVivek commented
The random crash is related to https://github.com/electron/electron/issues/20602

2023-03-28 06:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/responsively-org/responsively-app?pullRequest=400) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/responsively-org/responsively-app?pullRequest=400) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: esprush<br/>:x: manojVivek<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/responsively-org/responsively-app?pullRequest=400) it.</sub>

2026-08-02 05:31 UTC, esprush commented
Duplicate #1532

2026-08-02 05:31 UTC, closed without merging