fixed #457
responsively-org/responsively-app pull request #458
Opened 2020-09-17 13:31 UTC by MBakirci

2020-09-17 15:15 UTC, jjavierdguezas requested changes
Looks good @MBakirci thanks
please comment something in the issue to assign it to you

@MBakirci you are only handling this for Windows but I saw that space on Ubuntu too, should we address that too? @manojVivek 
![5bd1bd1a-fc43-4687-ae9f-e1d010728cc3](https://user-images.githubusercontent.com/13673443/93491748-5a685e80-f90a-11ea-87c0-ac748392964e.jpg)

2020-09-17 15:15 UTC, jjavierdguezas commented on desktop-app/app/components/Header/index.js
> -  const theme = useTheme();
if you removed this, please remove the `import` of `useTheme` on line `4`

2020-09-17 20:15 UTC, MBakirci commented
Thanks @jjavierdguezas. That is a good one, I only tested Responsively on Windows and Mac, but Linux has a lot of distros. I changed the line to `os.platform() === 'darwin' ?  '20px 0 5px' : '0 0 0'` and it works great on Ubuntu, but I don't know how it works on other distros.

2020-09-17 20:23 UTC, jjavierdguezas commented
@MBakirci I think this is OK, please comment in the issue #457 to assign the issue to you

2020-09-17 20:30 UTC, jjavierdguezas approved these changes

2020-09-17 20:30 UTC, merged

2020-09-17 20:31 UTC, jjavierdguezas commented
@MBakirci Thanks so much for your code contribution.
Looking forward to more collaboration in the future! 🙌

2020-09-17 20:32 UTC, jjavierdguezas commented
@all-contributors Please add @MBakirci for code.

2020-09-17 20:34 UTC, jjavierdguezas commented
@MBakirci Do you might sharing your Twitter handle? We would love to send a shout out for your work on twitter. :)

2020-09-18 03:03 UTC, manojVivek commented
@MBakirci Thanks for the contribution! 

Please join our slack workspace for any future discussions: https://join.slack.com/t/responsively/shared_invite/zt-haoieftz-IsMw64H6jXC23pJ16ROLzw :)