Feature screenshot all views
responsively-org/responsively-app pull request #900
Opened 2023-04-15 12:35 UTC by durgakiran

# ✨ Pull Request
Allows screen shot of all the screens

### 📓 Referenced Issue
closes #541 

### ℹ️ About the PR
- Adds Device name to the screenshot 
- Gives a button to capture screenshot of all devices
- Users existing screenshot flow to capture screens

### 🖼️ Testing Scenarios / Screenshots

2023-04-15 12:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/responsively-org/responsively-app?pullRequest=900) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/responsively-org/responsively-app?pullRequest=900) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/responsively-org/responsively-app?pullRequest=900) it.</sub>

2023-05-02 02:05 UTC, manojVivek requested changes
@durgakiran Thanks for implementing this feature. 🙌🏼 

Added a few minor code review comments. Also, we need to change the PR description a bit as this PR doesn't close #541, but a clear prerequisite for that one. 

When you're fixing the comment, please sign the CLA as well. 

I think, we can merge this with the current scope and then add the canvas output as the next iteration. Wdyt?

2023-05-02 02:05 UTC, manojVivek commented on desktop-app/src/renderer/components/ToolBar/index.tsx
> +        title="loading..."
```suggestion
        title="Screenshot"
```

2023-05-03 10:51 UTC, durgakiran commented on desktop-app/src/renderer/components/ToolBar/index.tsx
> +      const pageHeight = await webPage.getPageHeight();
This is not common, as this loop is specific to screenshot all functionality

2023-05-03 10:55 UTC, durgakiran commented on desktop-app/src/renderer/components/ToolBar/index.tsx
> +        title="loading..."
Updated

2023-05-03 10:55 UTC, durgakiran commented on desktop-app/src/renderer/components/ToolBar/index.tsx
> +    const devices = activeSuit.devices.map((d) => getDevicesMap()[d]);
Thanks for identifying type. Updated.

2023-05-03 10:56 UTC, durgakiran commented on desktop-app/src/renderer/components/ToolBar/index.tsx
> +  const activeSuit = useSelector(selectActiveSuite);
Thanks for identifying type, updated.

2023-05-03 10:57 UTC, durgakiran commented
> @durgakiran Thanks for implementing this feature. 🙌🏼
> 
> Added a few minor code review comments. Also, we need to change the PR description a bit as this PR doesn't close #541, but a clear prerequisite for that one.
> 
> When you're fixing the comment, please sign the CLA as well.
> 
> I think, we can merge this with the current scope and then add the canvas output as the next iteration. Wdyt?

Yes, That was my intention. Also, I have been working on the merge functionality with canvas output. Will soon raise but don't want to clutter to many things in one PR.

2023-05-03 11:55 UTC, manojVivek commented on desktop-app/src/renderer/components/ToolBar/index.tsx
> +      const pageHeight = await webPage.getPageHeight();
No, no, the loop is fine. 
I'm talking about the height and zoom adjusting logic from the single screenshot here: https://github.com/responsively-org/responsively-app/blob/main/desktop-app/src/renderer/components/Previewer/Device/Toolbar.tsx#L84-L90

2023-05-04 06:10 UTC, durgakiran commented on desktop-app/src/renderer/components/ToolBar/index.tsx
> +      const pageHeight = await webPage.getPageHeight();
oh ok

2023-05-04 06:23 UTC, durgakiran commented on desktop-app/src/renderer/components/ToolBar/index.tsx
> +      const pageHeight = await webPage.getPageHeight();
updated

2023-05-06 06:05 UTC, manojVivek approved these changes
Looking good! And thanks for your patience with the review!

2023-05-06 06:08 UTC, merged