Fixed screenshot transparent website
responsively-org/responsively-app pull request #960
Opened 2023-06-07 13:36 UTC by Ryan0204

# ✨ Pull Request

### 📓 Referenced Issue

- Fixed screenshot not working well for transparent background website [#959]

### ℹ️ About the PR

Fixed by adding below code
```js
...
await WebContents?.executeJavaScript(`
      const bgColor = window.getComputedStyle(document.body).backgroundColor;
      if (bgColor === 'rgba(0, 0, 0, 0)') {
        document.body.style.backgroundColor = 'white';
      } 
      window.isExecuted = true;
 `);
```

### 🖼️ Testing Scenarios / Screenshots

- Before 
![image](https://github.com/responsively-org/responsively-app/assets/82715592/44bb596a-bc62-4aa7-81d3-77452928a488)

- After 
![image](https://github.com/responsively-org/responsively-app/assets/82715592/896885fa-7913-4b67-9f5d-b6dcc3e70ef0)

2023-06-07 13:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/responsively-org/responsively-app?pullRequest=960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/responsively-org/responsively-app?pullRequest=960) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/responsively-org/responsively-app?pullRequest=960) it.</sub>

2023-06-16 16:41 UTC, themohammadsa commented
Hey @Ryan0204! This looks fantastic. Thanks for the super-fast contribution to this issue. 

Merging this, right away!

2023-06-16 16:52 UTC, themohammadsa requested changes
Hey @Ryan0204! 
This looks fantastic. Thanks for the super-fast contribution to this issue. 

Just a small change is required, could you undo your changes to the ```yarn.lock``` file? 
Can merge it right away after that! 🚀

2023-06-17 03:33 UTC, Ryan0204 commented
Sure, re-opening pr.

2023-06-17 13:08 UTC, themohammadsa commented
Lgtm! Merging this. 

Thank you, and hoping for more & more contributions in the future from your side! 😄

2023-06-17 13:10 UTC, merged

2023-06-17 13:15 UTC, themohammadsa commented
@all-contributors Please add @Ryan0204 for code.